[all:vars]
ansible_user=ec2-user
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i {{ bastion_key }} ec2-user@{{ bastion_ip }}"'

[app]
app_server ansible_host={{ app_private_ip }}